-- Seed sample data for maintenance_schedules

INSERT INTO maintenance_schedules (
    device_id,
    maintenance_type,
    maintenance_category,
    priority,
    scheduled_date,
    estimated_duration_hours,
    completed_date,
    actual_duration_hours,
    technician,
    technician_contact,
    cost,
    parts_replaced,
    tools_required,
    safety_precautions,
    pre_maintenance_readings,
    post_maintenance_readings,
    calibration_values,
    test_results,
    status,
    completion_rating,
    next_maintenance_date,
    maintenance_interval_days,
    warranty_impact,
    downtime_minutes,
    notes,
    maintenance_log,
    before_images,
    after_images,
    created_by
) VALUES
    (
        gen_random_uuid(),
        'cleaning',
        'preventive',
        'medium',
        CURRENT_DATE + INTERVAL '3 days',
        1.50,
        NULL,
        NULL,
        'Nguyen Van A',
        'a.nguyen@example.com',
        250.00,
        '[{"name": "Filter A", "quantity": 1}]'::jsonb,
        '["Brush", "Alcohol"]'::jsonb,
        'Wear gloves and goggles',
        '{"temperature": 32.5, "humidity": 70}'::jsonb,
        NULL,
        NULL,
        NULL,
        'scheduled',
        NULL,
        CURRENT_DATE + INTERVAL '33 days',
        30,
        FALSE,
        15,
        'Routine cleaning before peak season',
        'Step 1: Power off; Step 2: Clean filter; Step 3: Power on',
        '[]'::jsonb,
        '[]'::jsonb,
        gen_random_uuid()
    ),
    (
        gen_random_uuid(),
        'calibration',
        'routine',
        'high',
        CURRENT_DATE,
        2.00,
        CURRENT_DATE,
        2.10,
        'Tran Thi B',
        'b.tran@example.com',
        500.00,
        '[]'::jsonb,
        '["Calibrator", "Screwdriver"]'::jsonb,
        'Follow lockout-tagout procedures',
        '{"ph": 6.8}'::jsonb,
        '{"ph": 7.0}'::jsonb,
        '{"offset": 0.2}'::jsonb,
        'All tests passed',
        'completed',
        5,
        CURRENT_DATE + INTERVAL '90 days',
        90,
        FALSE,
        45,
        'Quarterly calibration as per SOP',
        'Adjusted sensor offset and verified readings',
        '[]'::jsonb,
        '[]'::jsonb,
        gen_random_uuid()
    ),
    (
        gen_random_uuid(),
        'repair',
        'corrective',
        'critical',
        CURRENT_DATE - INTERVAL '1 day',
        3.50,
        NULL,
        NULL,
        'Le Van C',
        'c.le@example.com',
        1200.00,
        '[{"name": "Pump X", "quantity": 1, "model": "PX-200"}]'::jsonb,
        '["Wrench", "Multimeter"]'::jsonb,
        'Disconnect power supply before handling',
        '{"flow_rate": 0}'::jsonb,
        NULL,
        NULL,
        NULL,
        'in_progress',
        NULL,
        NULL,
        NULL,
        TRUE,
        180,
        'Emergency repair due to pump failure',
        'Diagnosed pump motor; replacement in progress',
        '[]'::jsonb,
        '[]'::jsonb,
        gen_random_uuid()
    );


